cache:
  paths:
    - node_modules/
    - frontend/node_modules/

build:
  image: node:latest
  stage: build
  only:
    - main
  script:
    - npm run jenkins:build
  artifacts:
    paths:
      - frontend/build/**/*.*

shared:
  stage: deploy
  only:
    - main
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - scp -rp frontend/build/* $USERNAME@$HOST:$PATH_TO_WWW

heroku:
  image: ruby:latest
  stage: deploy
  only:
    - main
  script:
    - apt-get update -yq
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=qahelper-hu --api_key=$HEROKU_API_KEY
