image: node:latest

cache:
  paths:
    - node_modules/
    - frontend/node_modules/

build:
  stage: build
  script:
    - npm run jenkins:build
  artifacts:
    paths:
      - frontend/build/**/*.*

shared:
  stage: deploy
  script:
    - scp -i /storage/id_rsa -rp frontend/build/* $USERNAME@$HOST:$PATH_TO_WWW