export const SET_CURRENT_TIME = 'SET_CURRENT_TIME'
export const SET_HELLO_MESSAGE = 'SET_HELLO_MESSAGE'

export const SET_SEARCH_STRING = 'SET_SEARCH_STRING'
export const SET_SEARCH_RESET = 'SET_SEARCH_RESET'

export const ANSWER_LIST_REQUEST = 'ANSWER_LIST_REQUEST'
export const ANSWER_LIST_SUCCESS = 'ANSWER_LIST_SUCCESS'
export const ANSWER_LIST_FAIL = 'ANSWER_LIST_FAIL'

export const FILTERED_ANSWER_LIST_SET = 'FILTERED_ANSWER_LIST_SET'

export const SET_CATEGORY = 'SET_CATEGORY'
